# Generated by Django 5.1.1 on 2025-03-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApp', '0002_tag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='tertiary_colour',
            field=models.CharField(default='#0000FF', max_length=7),
        ),
    ]
