# Generated by Django 5.1.1 on 2025-03-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalApp', '0003_theme_tertiary_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='tertiary_colour',
            new_name='tertiary_color',
        ),
    ]
